### ISSUE TITLE
Property does not exist on channel "xfce4-desktop"

### ISSUE THREAD

**Issue by ronylee11** [Wolfyxon/xfce-live-wallpaper#2]
OS Kernel: arch linux-lts-5.15.41-1
DE: Xfce-4.16
WM: bspwm

Killing other wallpaper instances...
Done
Clearing cache...
nohup: appending output to 'nohup.out'
Converting GIF to image sequence, please wait...
Listing frames in /home/cleff/Public/xfce-live-wallpaper/cache
Running image sequence from: /home/cleff/Public/xfce-live-wallpaper/cache
Frames: 
['frame-9.png', 'frame-13.png', 'frame-3.png', 'frame-5.png', 'frame-20.png', 'frame-1.png', 'frame-22.png', 'frame-2.png', 'frame-17.png', 'frame-4.png', 'frame-6.png', 'frame-21.png', 'frame-8.png', 'frame-16.png', 'frame-23.png', 'frame-18.png', 'frame-0.png', 'frame-24.png', 'frame-15.png', 'frame-25.png', 'frame-12.png', 'frame-19.png', 'frame-14.png', 'frame-10.png', 'frame-7.png', 'frame-11.png']
Total: 26
Animating
Setting wallpaper to /home/cleff/Public/xfce-live-wallpaper/cache/frame-0.png

Error message: (Looped)
Property "/backdrop/screen0/monitor0/last-single-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Property "/backdrop/screen0/monitor0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Property "/backdrop/screen0/monitor0/image-path" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Property "/backdrop/screen0/monitoreDP-1/workspace0/last-image" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.

Fixed with:
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/last-single-image -t bool -s false --create
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -t bool -s false --create
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/last-image -t bool -s false --create
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP-1/workspace0/last-image -t bool -s false --create

**Comment by ronylee11** [comment]
Unable to convert "/home/cleff/Public/xfce-live-wallpaper/cache/frame-0.png" to type "gboolean"

**Comment by ronylee11** [comment]
Tried xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/last-single-image -t gboolean -s false --create
but it seems to not take gboolean as a type

Error:
Unable to determine the type of the value

**Comment by ronylee11** [comment]
Added -r at the end of commands in wallpaper.py

"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP-1/workspace0/last-image -s "+path + " -r",
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/last-image -s "+path + " -r",
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/last-single-image -s "+path + " -r",
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -s "+path + " -r"

script runs without error now, but background is not changed

**Comment by Wolfyxon** [comment]
try changing your wallpaper manually and see what property changes

**Comment by ronylee11** [comment]
Hi! Here's my output of xfconf-query -c xfce4-desktop -l
 
/backdrop/screen0/monitor0
/backdrop/screen0/monitorLVDS-0/workspace0/color-style
/backdrop/screen0/monitorLVDS-0/workspace0/image-style
/backdrop/screen0/monitorLVDS-0/workspace0/last-image
/backdrop/screen0/monitorLVDS-0/workspace1/color-style
/backdrop/screen0/monitorLVDS-0/workspace1/image-style
/backdrop/screen0/monitorLVDS-0/workspace1/last-image
/backdrop/screen0/monitorLVDS-0/workspace2/color-style
/backdrop/screen0/monitorLVDS-0/workspace2/image-style
/backdrop/screen0/monitorLVDS-0/workspace2/last-image
/backdrop/screen0/monitorLVDS-0/workspace3/color-style
/backdrop/screen0/monitorLVDS-0/workspace3/image-style
/backdrop/screen0/monitorLVDS-0/workspace3/last-image
/backdrop/screen0/monitorLVDS-0/workspace4/color-style
/backdrop/screen0/monitorLVDS-0/workspace4/image-style
/backdrop/screen0/monitorLVDS-0/workspace4/last-image
/backdrop/screen0/monitorLVDS-0/workspace5/color-style
/backdrop/screen0/monitorLVDS-0/workspace5/image-style
/backdrop/screen0/monitorLVDS-0/workspace5/last-image
/backdrop/screen0/monitorLVDS-0/workspace6/color-style
/backdrop/screen0/monitorLVDS-0/workspace6/image-style
/backdrop/screen0/monitorLVDS-0/workspace6/last-image
/backdrop/screen0/monitorLVDS-0/workspace7/color-style
/backdrop/screen0/monitorLVDS-0/workspace7/image-style
/backdrop/screen0/monitorLVDS-0/workspace7/last-image
/backdrop/screen0/monitorLVDS-0/workspace8/color-style
/backdrop/screen0/monitorLVDS-0/workspace8/image-style
/backdrop/screen0/monitorLVDS-0/workspace8/last-image
/backdrop/screen0/monitorLVDS-0/workspace9/color-style
/backdrop/screen0/monitorLVDS-0/workspace9/image-style
/backdrop/screen0/monitorLVDS-0/workspace9/last-image
/backdrop/single-workspace-mode
/backdrop/single-workspace-number
/desktop-icons/file-icons/show-filesystem
/desktop-icons/file-icons/show-home
/desktop-icons/file-icons/show-removable
/desktop-icons/file-icons/show-trash
/desktop-icons/gravity
/desktop-icons/style
/last/window-height
/last/window-width

i tried changing commands in wallpaper.py to
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace0/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace1/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace2/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace3/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace4/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace5/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace6/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace7/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace8/last-image -s "+path,
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace9/last-image -s "+path,

the background did changed but it kinda only picks up some frames, between frame-changes can take 7-8 seconds

**Comment by ronylee11** [comment]
Here is the output of xfconf-query -c xfce4-desktop -l -v 

Before i manually change background from Xfce Settings:

/backdrop/screen0/monitor0                              false
/backdrop/screen0/monitorLVDS-0/workspace0/color-style  3
/backdrop/screen0/monitorLVDS-0/workspace0/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace0/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace1/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace1/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace1/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace2/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace2/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace2/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace3/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace3/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace3/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace4/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace4/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace4/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace5/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace5/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace5/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace6/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace6/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace6/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace7/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace7/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace7/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace8/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace8/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace8/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace9/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace9/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace9/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/single-workspace-mode                         true
/backdrop/single-workspace-number                       0
/desktop-icons/file-icons/show-filesystem               false
/desktop-icons/file-icons/show-home                     false
/desktop-icons/file-icons/show-removable                false
/desktop-icons/file-icons/show-trash                    false
/desktop-icons/gravity                                  5
/desktop-icons/style                                    2
/last/window-height                                     572
/last/window-width                                      636

After i changed it from Xfce Settings:

/backdrop/screen0/monitor0                              false
/backdrop/screen0/monitorLVDS-0/workspace0/color-style  3
/backdrop/screen0/monitorLVDS-0/workspace0/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace0/last-image   /home/cleff/Pictures/tanjiro.jpg
/backdrop/screen0/monitorLVDS-0/workspace1/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace1/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace1/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace2/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace2/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace2/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace3/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace3/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace3/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace4/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace4/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace4/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace5/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace5/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace5/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace6/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace6/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace6/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace7/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace7/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace7/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace8/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace8/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace8/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/screen0/monitorLVDS-0/workspace9/color-style  0
/backdrop/screen0/monitorLVDS-0/workspace9/image-style  5
/backdrop/screen0/monitorLVDS-0/workspace9/last-image   /home/cleff/Public/xfce-live-wallpaper/cache/frame-8.png
/backdrop/single-workspace-mode                         true
/backdrop/single-workspace-number                       0
/desktop-icons/file-icons/show-filesystem               false
/desktop-icons/file-icons/show-home                     false
/desktop-icons/file-icons/show-removable                false
/desktop-icons/file-icons/show-trash                    false
/desktop-icons/gravity                                  5
/desktop-icons/style                                    2
/last/window-height                                     572
/last/window-width                                      636

**Comment by ronylee11** [comment]
got it working after changing the command to
"xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorLVDS-0/workspace0/last-image -s "+path,
it just takes some time to load, maybe my laptop is too old

**Comment by Wolfyxon** [comment]
Glad it worked. Yeah XFCE is very slow with reloading the wallpaper
