### ISSUE TITLE
Hi i Mode a Wallpaper engine based on your idea but more advanced -> https://github.com/Gmm09x/LinuxWallCraftEngine if your have idea for make this more good let me know contributions

### ISSUE THREAD

**Issue by ghost** [Wolfyxon/xfce-live-wallpaper#4]

**Comment by Wolfyxon** [comment]
Nice, I see you're also planning to support multiple DEs.

PS:
In future could you put things like links in the issue description? The title isn't really supposed to contain the whole issue data.
